### ISSUE TITLE
Make Python SDK the least possible wrapper around Requests

### ISSUE THREAD

**Issue by sgillies** [mapbox/geocoding-example#1]
@sbma44 @tmcw I'm a huge fan of [Requests](http://docs.python-requests.org/en/latest/) and so is the Python community. I'd like to help turn the Python geocoding example into the least wrapper around Requests with a usage like

``` python
>>> from mapbox_geocode import geocode
>>> r = geocode('YOUR_ACCESS_TOKEN', '1600 Pennsylvania Ave Washington, DC')
>>> r.status_code
200
>>> r.json()
{u'attribution': u'\xa9 2015 Mapbox and its suppliers. All rights reserved. Use of this data is subject to the Mapbox Terms of Service. (https://www.mapbox.com/about/maps/)', u'query': [u'1600', u'pennsylvania', u'ave', u'washington', u'dc'], u'type': u'FeatureCollection', u'features': [{u'center': [-77.036698, 38.897102], u'geometry': {u'type': u'Point', u'coordinates': [-77.036698, 38.897102]}, u'text': u'Pennsylvania Ave NW', u'properties': {}, u'bbox': [-77.05781199999998, 38.89252299999999, -77.01844799999999, [...]
```

Abstracting away all the network concerns bites when connectivity is poor or proxies are misbehaving.

**Comment by sbma44** [comment]
Discussed this a bit over at https://github.com/mapbox/geocoding-example/commit/b622cc9fc7900b4b49d1e31ddaef8bd6de2c5709#commitcomment-12171268 

Where I said:

> The simple case basically boils down to "make an http request and parse JSON" -- pretty basic stuff. I suspect that the population of people who need that example might include people who don't know how to install requests; the example as-is will run without complaint on any stock python install, including OS X.
> 
> I could be talked out of this but right now am leaning toward keeping it maximally simple.

I love `requests` and think we should use it in any non-trivial python examples, but it seems like there's value both for speed of implementation and lowering support issues in keeping our geocoding 101 examples dependency-free. But as I said, I could be talked out of this.
