### ISSUE TITLE
Proximity errors

### ISSUE THREAD

**Issue by tschaub** [mapbox/geocoding-example#2]
It looks like there have been some great improvements to the geocoding service recently.  I was interested to try out the [proximity option](https://www.mapbox.com/blog/geocoding-type-ahead/), and noticed some unexpected behavior (in edge cases).

For a request with bad proximity lon, lat, I get the expected `400`:
[https://api.tiles.mapbox.com/v4/geocode/mapbox.places-v1/seattle.json?proximity=-181,91](https://api.tiles.mapbox.com/v4/geocode/mapbox.places-v1/seattle.json?proximity=-181%2C91&access_token=pk.eyJ1IjoidHNjaGF1YiIsImEiOiI2TndKSnNjIn0.3Sc9yGKMUweACk0iG6HUbg)

``` json
{
  "message": "Bad Request"
}
```

For a request with a proximity lon, lat very near the edge of the world, I get a `502`:
[https://api.tiles.mapbox.com/v4/geocode/mapbox.places-v1/seattle.json?proximity=-180,89.95](https://api.tiles.mapbox.com/v4/geocode/mapbox.places-v1/seattle.json?proximity=-180%2C89.95&access_token=pk.eyJ1IjoidHNjaGF1YiIsImEiOiI2TndKSnNjIn0.3Sc9yGKMUweACk0iG6HUbg)

``` json
{
  "message": "Our servers are unreachable at this time."
}
```

For other proximity values at or near the edge, I get a `500`:
[https://api.tiles.mapbox.com/v4/geocode/mapbox.places-v1/seattle.json?proximity=-180,89.99](https://api.tiles.mapbox.com/v4/geocode/mapbox.places-v1/seattle.json?proximity=-180%2C89.99&access_token=pk.eyJ1IjoidHNjaGF1YiIsImEiOiI2TndKSnNjIn0.3Sc9yGKMUweACk0iG6HUbg)

``` json
{
  "message": "Internal Server Error"
}
```

Thanks for your continued work on this great service.  I know this is not the right repo for a ticket, but I wasn't sure where else to put it.

**Comment by yhahn** [comment]
@tschaub thanks for the report, looking into it now.

In the meantime I notice you're still using the old `mapbox.places-v1` endpoint -- definitely recommend updating to `mapbox.places` per our API docs here: https://www.mapbox.com/developers/api/geocoding/#forward

**Comment by tschaub** [comment]
Thanks for the heads-up on `mapbox.places` @yhahn.

**Comment by sbma44** [comment]
assuming this is now stale; please reopen if not @tschaub
