### ISSUE TITLE
add country, autocomplete, language flags

### ISSUE THREAD

**Issue by sbma44** [mapbox/geocoding-example#5]
cc @twbell -- I'll need to revisit this in the python & JS code as well once the flags are live in our docs

**Comment by twbell** [comment]
Done. https://github.com/mapbox/mapbox-sdk-php/blob/master/Mapbox.php#L92-L115  

Repo moved to new home at https://github.com/mapbox/mapbox-sdk-php

**Comment by sbma44** [comment]
\o/
