### ISSUE TITLE
Remove PHP Examples

### ISSUE THREAD

**Issue by twbell** [mapbox/geocoding-example#9]
The PHP SDK has moved to a more independent home.  Some items for clean-up:
1. Note in README that PHP SDK (incl. geocoding) has moved permanently to https://github.com/mapbox/mapbox-sdk-php
2. [Close all open tickets](https://github.com/mapbox/geocoding-example/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+php).
3. Remove php code

@sbma44 happy to do these, but require admin access

**Comment by sbma44** [comment]
oh man, apologies! I added the Mapbox team as admins.
